# Generated by Django 4.1.7 on 2023-06-14 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emcode', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('reason', models.CharField(max_length=1000)),
                ('date', models.DateField()),
            ],
        ),
    ]
